package io.mubel.sdk.execution;

import java.util.List;
import java.util.UUID;

/**
 * Result of a command execution.
 *
 * @param streamId      The stream id of the aggregate that the command was executed on.
 * @param newEventCount The number of events that was generated by the command.
 * @param oldVersion    The version of the aggregate before the command was executed.
 * @param newVersion    The version of the aggregate after the command was executed.
 * @param newEvents     The events that was generated by the command.
 *                      Note that these events will have been successfully appended to the event store
 *                      when this object is created.
 */
public record CommandResult<E>(
        UUID streamId,
        int newEventCount,
        int oldVersion,
        int newVersion,
        List<E> newEvents
) {

}
